version: '3.8'

services:
  db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    deploy:
      resources:
        limits:
          memory: ${DB_MEMORY_LIMIT}

  api:
    build: .
    command: uvicorn main:app --host ${API_HOST} --port ${API_PORT} --reload
    volumes:
      - ./app:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin

  import:
    build: .
    command: python import_geonames.py
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin
    deploy:
      resources:
        limits:
          memory: ${IMPORT_MEMORY_LIMIT}

volumes:
  mongo_data: